### ISSUE TITLE
CandidateServiceImpl required a bean of type 'CandidateMapper' 

### ISSUE THREAD

**Issue by arizeo** [dsl94/fileupload#1]
Hi

I am getting the following error when running the app in Intellij.

***************************
APPLICATION FAILED TO START
***************************

Description:

Field candidateMapper in com.ferrum.fileupload.service.impl.CandidateServiceImpl required a bean of type 'com.ferrum.fileupload.service.mapper.CandidateMapper' that could not be found.

Action:

Consider defining a bean of type 'com.ferrum.fileupload.service.mapper.CandidateMapper' in your configuration.

**Comment by dsl94** [comment]
Hi, after runing clean and install again and then running app there is no this error

**Comment by arizeo** [comment]
tks
